### ISSUE TITLE
Install Openstack on our Machines

### ISSUE THREAD

**Issue by lierseleow** [AurelWeinhold/calm#11]
Other Issues depend on Openstack being installed on our Machines.

The Stakeholders prefer us using [kolla-ansible](https://docs.openstack.org/kolla-ansible/latest/)
See #13

- [x] Run Pre-Bootstrap successfully (#27)
- [x] Run Bootstrap successfully (#28)
- [x] Run Pre-Checks successfully (#30)
- [x] Run Deployment successfully (#29)

**Comment by AurelWeinhold** [comment]
What do you mean with "our machines"? The server, or actually our own PCs?

**Comment by lierseleow** [comment]
> What do you mean with "our machines"? The server, or actually our own PCs?

With "our machines" i mean the 4 servers we were lent from the cit for our project.
